### ISSUE TITLE
No version tag in docker hub

### ISSUE THREAD

**Issue by arulrajnet** [komljen/docker-filebeat#2]
This docker pushed to [here](https://hub.docker.com/r/komljen/filebeat/tags/) with latest as version tag.

The version of filebeat in Dockerfile is 5.3.2. So could you tag the docker also in the same way.

**Comment by komljen** [comment]
Thanks for the pointing that out. All new images will be tagged with the filebeat version.

**Comment by komljen** [comment]
At the moment komljen/filebeat:5.3.2 is available.
